epochs: 300
vqgan_path: ?
model:
  batch_size: 10
  diffusion_img_size: 32
  dimension_mults: [1 2 4 8]
  diffusion_num_channels: 8
  diffusion_depth_size: 32
  timesteps: 1000
  loss_type: l1
  ema_decay: 0.995
  learning_rate: 1e-4
  amp: False
dataset:
  root_dir: ?
  image_channels: 1
  
